### ISSUE TITLE
Coursera cannot be reached

### ISSUE THREAD

**Issue by BharathMuralidhar** [Gautamji/borg#19]
Borg doesn't seem to reach Coursera when I try to "Add Course". Edx and some others do not respond similarly. Screenshot of error message attached.
![image](https://cloud.githubusercontent.com/assets/6504511/18224788/9947d08c-71fe-11e6-811e-8b74f8d7775e.png)

**Comment by Gautamji** [comment]
please check #1 for solution
a permanent fix is on the way

**Comment by abhi1109** [comment]
hey, Gautam, from one month I'm also facing the same problem. Tried your solution,  But it didn't work for me. Any update on the fix. Please let us know.

**Comment by abhi1109** [comment]
The problem is with the Coursera only.

**Comment by Gautamji** [comment]
remove user.cookies and try again.
