### ISSUE TITLE
Unable to find a valid youtube url

### ISSUE THREAD

**Issue by hacback17** [Gautamji/borg#36]
I was trying to download youtube videos. But it could not find the url even though it is a valid url. Here is a screenshot below:

![image](https://cloud.githubusercontent.com/assets/14871809/20371755/f98eb5aa-ac8c-11e6-8337-b6556903d671.png)

You can try the url yourself:- https://www.youtube.com/watch?v=MX2Jvnsjsco&list=TLGGAxhuILEn10kxNjExMjAxNg

**Comment by Gautamji** [comment]
I have noticed some differences between this playlist and other playlists which is the source of the problem.
![screen shot 2016-11-18 at 2 20 43 pm](https://cloud.githubusercontent.com/assets/4068661/20424142/5e2792a8-ad9a-11e6-8fe9-cb11b0145234.png)
![screen shot 2016-11-18 at 2 21 01 pm](https://cloud.githubusercontent.com/assets/4068661/20424143/5e2f5dee-ad9a-11e6-9e44-fdf0c2633c77.png)

As you can see, your url has an untitled playlist and the playlist name is not clickable and there is no "+" sign at the end of its name.
Which means that this playlist cannot be opened in its own page. Which is probably why Borg can't find it.
The solution is to make your own playlist using the videos from this playlist and then import it into Borg.

Here I have done it for you : https://www.youtube.com/playlist?list=PLuttsTytyW6MzBd7Dq_e6qIYWGMwckt28

**Comment by hacback17** [comment]
I got it. Thanks for the solution.
Another issue I have noticed is if the video size is large Borg sometimes downloads only half part and pretends as if the download is complete.

**Comment by Gautamji** [comment]
You will have to send me an example for that too.

**Comment by hacback17** [comment]
Sure. I will soon...

**Comment by Gautamji** [comment]
On a new thread, I am closing this issue as resolved

**Comment by hacback17** [comment]
Okay
